In [98]:
import pandas as pd
import tensorflow as tf
import sklearn

In [99]:
pd.__version__, tf.__version__, sklearn.__version__

('2.2.3', '2.16.1', '1.5.2')

In [100]:
from tensorflow.keras.layers import Dense, Dropout, Activation, Input
from tensorflow.keras.models import Model
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [101]:
base = pd.read_csv('C:/Users/nanojau/OneDrive/Documentos/CURSOS/DeepLearningWithPythonUdemy/games.csv',encoding='ISO-8859-1')
base

Name Platform  Year_of_Release         Genre  \
0                         Wii Sports      Wii           2006.0        Sports   
1                  Super Mario Bros.      NES           1985.0      Platform   
2                     Mario Kart Wii      Wii           2008.0        Racing   
3                  Wii Sports Resort      Wii           2009.0        Sports   
4           Pokemon Red/Pokemon Blue       GB           1996.0  Role-Playing   
...                              ...      ...              ...           ...   
16714  Samurai Warriors: Sanada Maru      PS3           2016.0        Action   
16715               LMA Manager 2007     X360           2006.0        Sports   
16716        Haitaka no Psychedelica      PSV           2016.0     Adventure   
16717               Spirits & Spells      GBA           2003.0      Platform   
16718            Winning Post 8 2016      PSV           2016.0    Simulation   

          Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  \
0          Nintendo     41.36     28.96      3.77         8.45         82.53   
1          Nintendo     29.08      3.58      6.81         0.77         40.24   
2          Nintendo     15.68     12.76      3.79         3.29         35.52   
3          Nintendo     15.61     10.93      3.28         2.95         32.77   
4          Nintendo     11.27      8.89     10.22         1.00         31.37   
...             ...       ...       ...       ...          ...           ...   
16714    Tecmo Koei      0.00      0.00      0.01         0.00          0.01   
16715   Codemasters      0.00      0.01      0.00         0.00          0.01   
16716  Idea Factory      0.00      0.00      0.01         0.00          0.01   
16717       Wanadoo      0.01      0.00      0.00         0.00          0.01   
16718    Tecmo Koei      0.00      0.00      0.01         0.00          0.01   

       Critic_Score  Critic_Count User_Score  User_Count Developer Rating  
0              76.0          51.0          8       322.0  Nintendo      E  
1               NaN           NaN        NaN         NaN       NaN    NaN  
2              82.0          73.0        8.3       709.0  Nintendo      E  
3              80.0          73.0          8       192.0  Nintendo      E  
4               NaN           NaN        NaN         NaN       NaN    NaN  
...             ...           ...        ...         ...       ...    ...  
16714           NaN           NaN        NaN         NaN       NaN    NaN  
16715           NaN           NaN        NaN         NaN       NaN    NaN  
16716           NaN           NaN        NaN         NaN       NaN    NaN  
16717           NaN           NaN        NaN         NaN       NaN    NaN  
16718           NaN           NaN        NaN         NaN       NaN    NaN  

[16719 rows x 16 columns]

In [102]:
base = base.drop("Other_Sales", axis = 1)
base = base.drop("Global_Sales", axis = 1)
base = base.drop("Developer", axis = 1)


In [103]:
base.shape

(16719, 13)

In [104]:
base.isnull().sum()

Name                  2
Platform              0
Year_of_Release     269
Genre                 2
Publisher            54
NA_Sales              0
EU_Sales              0
JP_Sales              0
Critic_Score       8582
Critic_Count       8582
User_Score         6704
User_Count         9129
Rating             6769
dtype: int64

In [105]:
base = base.dropna(axis = 0)

In [106]:
base.shape

(6825, 13)

In [107]:
base.isnull().sum()

Name               0
Platform           0
Year_of_Release    0
Genre              0
Publisher          0
NA_Sales           0
EU_Sales           0
JP_Sales           0
Critic_Score       0
Critic_Count       0
User_Score         0
User_Count         0
Rating             0
dtype: int64

In [108]:
base["Name"].value_counts

<bound method IndexOpsMixin.value_counts of 0                               Wii Sports
2                           Mario Kart Wii
3                        Wii Sports Resort
6                    New Super Mario Bros.
7                                 Wii Play
                       ...                
16667           E.T. The Extra-Terrestrial
16677       Mortal Kombat: Deadly Alliance
16696    Metal Gear Solid V: Ground Zeroes
16700                               Breach
16706              STORM: Frontline Nation
Name: Name, Length: 6825, dtype: object>

In [109]:
base = base.drop('Name', axis = 1)

In [110]:
base.shape

(6825, 12)

In [111]:
base.columns

Index(['Platform', 'Year_of_Release', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Critic_Score', 'Critic_Count', 'User_Score',
       'User_Count', 'Rating'],
      dtype='object')

In [112]:
X = base.iloc[:, [0, 1, 2, 3, 7, 8, 9, 10, 11]].values
X

array([['Wii', 2006.0, 'Sports', ..., '8', 322.0, 'E'],
       ['Wii', 2008.0, 'Racing', ..., '8.3', 709.0, 'E'],
       ['Wii', 2009.0, 'Sports', ..., '8', 192.0, 'E'],
       ...,
       ['PC', 2014.0, 'Action', ..., '7.6', 412.0, 'M'],
       ['PC', 2011.0, 'Shooter', ..., '5.8', 43.0, 'T'],
       ['PC', 2011.0, 'Strategy', ..., '7.2', 13.0, 'E10+']], dtype=object)

In [113]:
y_na = base.iloc[:, 4].values
y_eu = base.iloc[:, 5].values
y_jp = base.iloc[:, 6].values

In [114]:
#PS2  1 0 0 0 ....
#Xbox 1 0 0 0...
base['Platform'].value_counts()

Platform
PS2     1140
X360     858
PS3      769
PC       651
XB       565
Wii      479
DS       464
PSP      390
GC       348
PS4      239
GBA      237
XOne     159
3DS      155
PS       150
PSV      118
WiiU      89
DC        14
Name: count, dtype: int64

In [115]:
base.columns

Index(['Platform', 'Year_of_Release', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Critic_Score', 'Critic_Count', 'User_Score',
       'User_Count', 'Rating'],
      dtype='object')

In [116]:
oneHotEncoder = ColumnTransformer(transformers=[("OneHot",OneHotEncoder(), [0, 2, 3, 8])], remainder='passthrough')
X = oneHotEncoder.fit_transform(X).toarray()

In [117]:
X.shape

(6825, 303)

In [118]:
X[0]

array([0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 

In [119]:
(303+3)/2

153.0

In [120]:
camada_entrada = Input(shape = (303,))
camada_oculta = Dense(units= 153, activation='relu')(camada_entrada)
camada_oculta2 = Dense(units= 153, activation='relu')(camada_oculta)
camada_saida = Dense(units=1,activation='linear')(camada_oculta2)
camada_saida2 = Dense(units=1,activation='linear')(camada_oculta2)
camada_saida3 = Dense(units=1,activation='linear')(camada_oculta2)


In [121]:
regressor = Model(inputs = camada_entrada, outputs = [camada_saida, camada_saida2,camada_saida3])

In [122]:
#Compilação da Rede Neural
regressor.compile(optimizer = 'adam', loss = 'mse')

In [ ]:
regressor.fit(X, [y_na, y_eu, y_jp], epochs= 500, batch_size=100)

Epoch 1/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - dense_20_loss: 3453.7107 - dense_21_loss: 527.7477 - dense_22_loss: 868.8784 - loss: 4850.8184 
Epoch 2/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - dense_20_loss: 4.3051 - dense_21_loss: 8.5817 - dense_22_loss: 2.7771 - loss: 15.6652
Epoch 3/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - dense_20_loss: 2.5753 - dense_21_loss: 1.6925 - dense_22_loss: 0.5826 - loss: 4.8508
Epoch 4/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - dense_20_loss: 3.5351 - dense_21_loss: 3.0777 - dense_22_loss: 1.3546 - loss: 7.9692
Epoch 5/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - dense_20_loss: 1.9655 - dense_21_loss: 0.6579 - dense_22_loss: 0.3119 - loss: 2.9358
Epoch 6/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - dense_20_loss: 3.2821 - dense_21_loss: 1.2054 - dense_22_loss: 0.3564 - loss: 4.8428
Epoch 7/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - dense_20_loss: 2.2419 - dense_21_loss: 1.9827 - dense_22_loss: 0.9423 - loss: 5.1701
Epoch 8/500
69/69 ━━━━

In [88]:
previsao_na, previsao_eu, previsao_jp = regressor.predict(X)

214/214 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


In [89]:
previsao_na, previsao_na.mean()

(array([[0.6279221 ],
        [0.9038515 ],
        [0.6318238 ],
        ...,
        [0.40702233],
        [0.21067381],
        [0.12696493]], dtype=float32),
 0.34978223)

In [91]:
y_na, y_na.mean()

(array([4.136e+01, 1.568e+01, 1.561e+01, ..., 0.000e+00, 1.000e-02,
        0.000e+00]),
 0.3944835164835165)

In [92]:
from sklearn.metrics import mean_absolute_error

In [93]:
mean_absolute_error(y_na, previsao_na)

0.32642003684690146

In [90]:
previsao_eu, previsao_eu.mean()

(array([[ 0.33757648],
        [ 0.59754604],
        [ 0.34032744],
        ...,
        [ 0.18182555],
        [ 0.04338509],
        [-0.01563591]], dtype=float32),
 0.14977655)

In [94]:
y_eu, y_eu.mean()

(array([2.896e+01, 1.276e+01, 1.093e+01, ..., 1.000e-02, 0.000e+00,
        1.000e-02]),
 0.23608937728937732)

In [ ]:
mean_absolute_error(y_eu, previsao_eu)

In [96]:
previsao_jp, previsao_jp.mean()

(array([[ 0.10412107],
        [ 0.13658203],
        [ 0.10503969],
        ...,
        [ 0.05211196],
        [ 0.00588326],
        [-0.01382533]], dtype=float32),
 0.03450647)

In [97]:
y_jp, y_jp.mean()

(array([3.77, 3.79, 3.28, ..., 0.  , 0.  , 0.  ]), 0.06415824175824175)

In [ ]:
mean_absolute_error(y_eu, previsao_jp)