In [1]:
import numpy as np
import pandas as pd
import matplotlib
import tensorflow as tf
import sklearn

In [2]:
np.__version__, pd.__version__, matplotlib.__version__, tf.__version__, sklearn.__version__

('1.26.4', '2.2.3', '3.10.0', '2.16.1', '1.5.2')

In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import InputLayer, Dense, Dropout, LSTM
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt

In [4]:

base = pd.read_csv("C:/Users/nanojau/OneDrive/Documentos/CURSOS/DeepLearningWithPythonUdemy/petr4_treinamento.csv")
base = base.dropna()
base

Date       Open       High        Low      Close  Adj Close  \
0     2013-01-02  19.990000  20.209999  19.690001  19.690001  18.086271   
1     2013-01-03  19.809999  20.400000  19.700001  20.400000  18.738441   
2     2013-01-04  20.330000  20.620001  20.170000  20.430000  18.766001   
3     2013-01-07  20.480000  20.670000  19.950001  20.080000  18.444506   
4     2013-01-08  20.110001  20.230000  19.459999  19.500000  17.911745   
...          ...        ...        ...        ...        ...        ...   
1240  2017-12-25  15.750000  15.750000  15.750000  15.750000  15.718563   
1241  2017-12-26  15.750000  15.990000  15.690000  15.970000  15.938125   
1242  2017-12-27  15.990000  16.139999  15.980000  16.049999  16.017963   
1243  2017-12-28  16.100000  16.129999  16.000000  16.100000  16.067865   
1244  2017-12-29  16.100000  16.100000  16.100000  16.100000  16.067865   

          Volume  
0     30182600.0  
1     30552600.0  
2     36141000.0  
3     28069600.0  
4     29091300.0  
...          ...  
1240         0.0  
1241  22173100.0  
1242  23552200.0  
1243  19011500.0  
1244         0.0  

[1242 rows x 7 columns]

In [5]:
base_treinamento = base.iloc[:, 1:7].values

In [6]:
base_treinamento

array([[1.9990000e+01, 2.0209999e+01, 1.9690001e+01, 1.9690001e+01,
        1.8086271e+01, 3.0182600e+07],
       [1.9809999e+01, 2.0400000e+01, 1.9700001e+01, 2.0400000e+01,
        1.8738441e+01, 3.0552600e+07],
       [2.0330000e+01, 2.0620001e+01, 2.0170000e+01, 2.0430000e+01,
        1.8766001e+01, 3.6141000e+07],
       ...,
       [1.5990000e+01, 1.6139999e+01, 1.5980000e+01, 1.6049999e+01,
        1.6017963e+01, 2.3552200e+07],
       [1.6100000e+01, 1.6129999e+01, 1.6000000e+01, 1.6100000e+01,
        1.6067865e+01, 1.9011500e+07],
       [1.6100000e+01, 1.6100000e+01, 1.6100000e+01, 1.6100000e+01,
        1.6067865e+01, 0.0000000e+00]])

In [7]:
normalizador = MinMaxScaler(feature_range=(0,1))
base_treinamento_normalizada = normalizador.fit_transform(base_treinamento)

In [8]:
base_treinamento_normalizada

array([[0.76501938, 0.77266112, 0.79682707, 0.76080559, 0.6838135 ,
        0.04318274],
       [0.7562984 , 0.78187106, 0.79733884, 0.79567784, 0.71590949,
        0.0437121 ],
       [0.78149225, 0.79253519, 0.82139202, 0.79715132, 0.71726583,
        0.05170752],
       ...,
       [0.57122093, 0.57537562, 0.60696008, 0.58202356, 0.58202349,
        0.03369652],
       [0.57655039, 0.57489089, 0.60798362, 0.5844794 , 0.58447937,
        0.02720006],
       [0.57655039, 0.57343674, 0.61310133, 0.5844794 , 0.58447937,
        0.        ]])

In [9]:
X = [] #previsores
y = [] #preço real
for i in range(90, 1242): # preço real será previsot em relação aos 90 preços anteriores
    X.append(base_treinamento_normalizada[i - 90:i, 0:6])
    y.append(base_treinamento_normalizada[i, 0])
print(i, i-90)
X, y  = np.array(X), np.array(y)

1241 1151


In [11]:
X[0]

array([[0.76501938, 0.77266112, 0.79682707, 0.76080559, 0.6838135 ,
        0.04318274],
       [0.7562984 , 0.78187106, 0.79733884, 0.79567784, 0.71590949,
        0.0437121 ],
       [0.78149225, 0.79253519, 0.82139202, 0.79715132, 0.71726583,
        0.05170752],
       [0.78875969, 0.7949588 , 0.81013311, 0.77996075, 0.70144373,
        0.04015963],
       [0.77083338, 0.77363063, 0.78505624, 0.75147351, 0.67522435,
        0.0416214 ],
       [0.74806197, 0.75618037, 0.78505624, 0.76031438, 0.68336137,
        0.03485382],
       [0.75436047, 0.76490543, 0.78915051, 0.76768177, 0.69014234,
        0.02507502],
       [0.75823643, 0.76442079, 0.79733884, 0.77013751, 0.6924025 ,
        0.0260728 ],
       [0.76598837, 0.77411537, 0.79682707, 0.76227897, 0.68516964,
        0.0404927 ],
       [0.76598837, 0.77411537, 0.79682707, 0.76719061, 0.68969016,
        0.0423977 ],
       [0.76017437, 0.75714973, 0.79222108, 0.76817293, 0.69059437,
        0.02401858],
       [0.75872098, 0

In [13]:
X.shape

(1152, 90, 6)

In [12]:
y.shape

(1152,)

In [14]:
regressor = Sequential()

regressor.add(LSTM(units = 100, return_sequences=True, input_shape = (X.shape[1], 6)))
regressor.add(Dropout(0.3))

regressor.add(LSTM(units = 50, return_sequences=True))
regressor.add(Dropout(0.3))

regressor.add(LSTM(units = 50, return_sequences=True))
regressor.add(Dropout(0.3))

regressor.add(LSTM(units = 50))
regressor.add(Dropout(0.3))

regressor.add(Dense(units = 1, activation = 'linear'))

regressor.summary()

C:\Users\nanojau\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 90, 100)        │        42,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 90, 100)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 90, 50)         │        30,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 90, 50)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 90, 50)         │        20,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 90, 50)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ (None, 50)             │        20,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 50)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            51 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 113,451 (443.17 KB)

 Trainable params: 113,451 (443.17 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
regressor.compile(optimizer='adam', loss = 'mean_squared_error',metrics = ['mean_absolute_error'])

In [18]:
#Função utilizada para interromper o treinamento caso o valor do erro não melhore após um número determinado de épocas
es = EarlyStopping(monitor='loss', min_delta=1e-10, patience=10, verbose=True) #0.0000000...1
rlr = ReduceLROnPlateau(monitor='loss', factor=0.2, patience=5, verbose=1)
mcp = ModelCheckpoint(filepath='pesos.keras', monitor='loss', save_best_only=True, verbose = 1)

In [19]:
regressor.fit(X, y, epochs=100, batch_size=32, callbacks=[es, rlr,mcp])

Epoch 1/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - loss: 0.0474 - mean_absolute_error: 0.1577
Epoch 1: loss improved from inf to 0.02298, saving model to pesos.keras
36/36 ━━━━━━━━━━━━━━━━━━━━ 9s 112ms/step - loss: 0.0467 - mean_absolute_error: 0.1564 - learning_rate: 0.0010
Epoch 2/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - loss: 0.0104 - mean_absolute_error: 0.0785
Epoch 2: loss improved from 0.02298 to 0.00955, saving model to pesos.keras
36/36 ━━━━━━━━━━━━━━━━━━━━ 4s 115ms/step - loss: 0.0104 - mean_absolute_error: 0.0784 - learning_rate: 0.0010
Epoch 3/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - loss: 0.0082 - mean_absolute_error: 0.0686
Epoch 3: loss improved from 0.00955 to 0.00803, saving model to pesos.keras
36/36 ━━━━━━━━━━━━━━━━━━━━ 4s 111ms/step - loss: 0.0082 - mean_absolute_error: 0.0686 - learning_rate: 0.0010
Epoch 4/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 0.0080 - mean_absolute_error: 0.0687
Epoch 4: loss improved from 0.00803 to 0.00797, saving