In [33]:
import numpy as np
import tensorflow as tf
import pandas as pd

In [34]:
np.__version__, tf.__version__

('1.26.4', '2.16.1')

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt

In [36]:
base = pd.read_csv("C:/Users/nanojau/OneDrive/Documentos/CURSOS/DeepLearningWithPythonUdemy/petr4_treinamento.csv")
base

Date       Open       High        Low      Close  Adj Close  \
0     2013-01-02  19.990000  20.209999  19.690001  19.690001  18.086271   
1     2013-01-03  19.809999  20.400000  19.700001  20.400000  18.738441   
2     2013-01-04  20.330000  20.620001  20.170000  20.430000  18.766001   
3     2013-01-07  20.480000  20.670000  19.950001  20.080000  18.444506   
4     2013-01-08  20.110001  20.230000  19.459999  19.500000  17.911745   
...          ...        ...        ...        ...        ...        ...   
1240  2017-12-25  15.750000  15.750000  15.750000  15.750000  15.718563   
1241  2017-12-26  15.750000  15.990000  15.690000  15.970000  15.938125   
1242  2017-12-27  15.990000  16.139999  15.980000  16.049999  16.017963   
1243  2017-12-28  16.100000  16.129999  16.000000  16.100000  16.067865   
1244  2017-12-29  16.100000  16.100000  16.100000  16.100000  16.067865   

          Volume  
0     30182600.0  
1     30552600.0  
2     36141000.0  
3     28069600.0  
4     29091300.0  
...          ...  
1240         0.0  
1241  22173100.0  
1242  23552200.0  
1243  19011500.0  
1244         0.0  

[1245 rows x 7 columns]

In [37]:
base.isnull().sum()

Date         0
Open         3
High         3
Low          3
Close        3
Adj Close    3
Volume       3
dtype: int64

In [38]:
base = base.dropna()

In [39]:
base.shape

(1242, 7)

In [40]:
base_treinamento = base.iloc[:, 1:2].values

In [41]:
base_treinamento

array([[19.99    ],
       [19.809999],
       [20.33    ],
       ...,
       [15.99    ],
       [16.1     ],
       [16.1     ]])

In [42]:
#Normalização dos dados
normalizador = MinMaxScaler(feature_range=(0,1))
base_treinamento_normalizada = normalizador.fit_transform(base_treinamento)
base_treinamento_normalizada

array([[0.76501938],
       [0.7562984 ],
       [0.78149225],
       ...,
       [0.57122093],
       [0.57655039],
       [0.57655039]])

In [43]:
base_treinamento_normalizada.shape

(1242, 1)

In [44]:
X = [] #previsores
y = [] #preço real
for i in range(90, 1242): # preço real será previsot em relação aos 90 preços anteriores
    X.append(base_treinamento_normalizada[i - 90:i, 0])
    y.append(base_treinamento_normalizada[i, 0])
print(i, i-90)
X, y  = np.array(X), np.array(y)

1241 1151


In [45]:
X.shape

(1152, 90)

In [46]:
y.shape

(1152,)

In [47]:
X[0] , y[0]

(array([0.76501938, 0.7562984 , 0.78149225, 0.78875969, 0.77083338,
        0.74806197, 0.75436047, 0.75823643, 0.76598837, 0.76598837,
        0.76017437, 0.75872098, 0.75581391, 0.74467054, 0.7374031 ,
        0.7374031 , 0.73498067, 0.75242248, 0.73401163, 0.71656977,
        0.68120155, 0.67538755, 0.67635659, 0.63372098, 0.66521318,
        0.65649225, 0.64680228, 0.66618222, 0.65843028, 0.64970935,
        0.65116274, 0.66424419, 0.67344961, 0.64292631, 0.64486434,
        0.62257747, 0.60949617, 0.60998067, 0.60852713, 0.59593023,
        0.61143411, 0.60222863, 0.64922481, 0.68362398, 0.70687989,
        0.68265509, 0.70978682, 0.70784879, 0.71608527, 0.73643411,
        0.7122093 , 0.7122093 , 0.7194767 , 0.70348832, 0.69525189,
        0.70397287, 0.70397287, 0.69767442, 0.68168605, 0.68168605,
        0.65310078, 0.66618222, 0.64825581, 0.66182175, 0.64341085,
        0.67877902, 0.69137592, 0.66569772, 0.65406982, 0.64292631,
        0.64147292, 0.63565891, 0.67587209, 0.68

In [ ]:
regressor = Sequential()

regressor.add(LSTM(units = 100, return_sequences=True, input_shape = (X.shape[1], 1)))
regressor.add(Dropout(0.3))

regressor.add(LSTM(units = 50, return_sequences=True))
regressor.add(Dropout(0.3))

regressor.add(LSTM(units = 50, return_sequences=True))
regressor.add(Dropout(0.3))

regressor.add(LSTM(units = 50))
regressor.add(Dropout(0.3))

regressor.add(Dense(units = 1, activation = 'linear'))

regressor.summary()

C:\Users\nanojau\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 90, 100)        │        40,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 90, 100)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 90, 50)         │        30,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 90, 50)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 90, 50)         │        20,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 90, 50)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ (None, 50)             │        20,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 50)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            51 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 111,451 (435.36 KB)

 Trainable params: 111,451 (435.36 KB)

 Non-trainable params: 0 (0.00 B)

In [51]:
regressor.compile(optimizer='rmsprop', loss = 'mean_squared_error',metrics = ['mean_absolute_error'])

In [52]:
regressor.fit(X, y , epochs= 100, batch_size= 32)

Epoch 1/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 9s 113ms/step - loss: 0.0582 - mean_absolute_error: 0.1847
Epoch 2/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 4s 108ms/step - loss: 0.0141 - mean_absolute_error: 0.0922
Epoch 3/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 4s 108ms/step - loss: 0.0137 - mean_absolute_error: 0.0926
Epoch 4/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 4s 110ms/step - loss: 0.0136 - mean_absolute_error: 0.0907
Epoch 5/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 4s 110ms/step - loss: 0.0081 - mean_absolute_error: 0.0693
Epoch 6/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 4s 110ms/step - loss: 0.0097 - mean_absolute_error: 0.0760
Epoch 7/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 4s 108ms/step - loss: 0.0079 - mean_absolute_error: 0.0688
Epoch 8/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 4s 105ms/step - loss: 0.0078 - mean_absolute_error: 0.0673
Epoch 9/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 4s 107ms/step - loss: 0.0069 - mean_absolute_error: 0.0658
Epoch 10/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 4s 110ms/step - loss: 0.0066 - mean_absolute_error: 0.0621
Epoch 11/100
36/36 

In [55]:
base_teste = pd.read_csv("C:/Users/nanojau/OneDrive/Documentos/CURSOS/DeepLearningWithPythonUdemy/petr4_teste.csv")
base_teste

Date       Open       High        Low      Close  Adj Close  \
0   2018-01-02  16.190001  16.549999  16.190001  16.549999  16.516966   
1   2018-01-03  16.490000  16.719999  16.370001  16.700001  16.666668   
2   2018-01-04  16.780001  16.959999  16.620001  16.730000  16.696608   
3   2018-01-05  16.700001  16.860001  16.570000  16.830000  16.796408   
4   2018-01-08  16.740000  17.030001  16.709999  17.030001  16.996010   
5   2018-01-09  17.030001  17.160000  16.959999  17.030001  16.996010   
6   2018-01-10  16.920000  17.049999  16.770000  16.799999  16.766466   
7   2018-01-11  16.879999  17.299999  16.840000  17.250000  17.215569   
8   2018-01-12  17.040001  17.410000  17.020000  17.299999  17.265469   
9   2018-01-15  17.320000  17.440001  17.150000  17.350000  17.315371   
10  2018-01-16  17.350000  17.840000  17.299999  17.650000  17.614771   
11  2018-01-17  17.920000  18.360001  17.809999  18.360001  18.323355   
12  2018-01-18  18.350000  18.530001  17.930000  18.219999  18.183632   
13  2018-01-19  18.309999  18.420000  18.030001  18.260000  18.223553   
14  2018-01-22  18.260000  18.469999  18.090000  18.469999  18.433134   
15  2018-01-23  18.400000  18.459999  18.000000  18.240000  18.203592   
16  2018-01-24  18.420000  19.629999  18.420000  19.340000  19.301397   
17  2018-01-25  19.340000  19.340000  19.340000  19.340000  19.301397   
18  2018-01-26  19.620001  19.980000  19.100000  19.930000  19.890221   
19  2018-01-29  19.670000  20.049999  19.570000  19.850000  19.810381   
20  2018-01-30  19.770000  19.770000  19.360001  19.490000  19.451097   
21  2018-01-31  19.740000  19.930000  19.680000  19.700001  19.660681   

      Volume  
0   33461800  
1   55940900  
2   37064900  
3   26958200  
4   28400000  
5   35070900  
6   28547700  
7   37921500  
8   45912100  
9   28945400  
10  58618300  
11  58488900  
12  48575800  
13  33470200  
14  33920000  
15  35567700  
16  89768200  
17         0  
18  81989500  
19  55726200  
20  46203000  
21  41576600